version: '3.3'
services:
  authdb:
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'authdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
      # Where our data will be persisted
    expose:
      - '3306'
