version: '3.3'
services:
  authdb:
    hostname: authdb
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'authdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
      # Where our data will be persisted

  message-broker:
    image: rabbitmq:3.8-management
    hostname: message-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  guilddb:
    hostname: guilddb
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'guilddb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'

  jking-auth:
    build: ../authentication
    depends_on:
      - authdb
      - message-broker
    image: jking-auth
    hostname: jking-auth
    restart: always
    ports:
      - 8082:8082

  jking-guild:
    build: ../guild
    depends_on:
      - guilddb
      - message-broker
    image: jking-guild
    hostname: jking-guild
    restart: always
    ports:
      - 8081:8081
