apiVersion: apps/v1
kind: Deployment
metadata:
  name: authdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authdb
  template:
    metadata:
      labels:
        app: authdb
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: authdb
          image: mysql:8.0.20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 3306
              name: authdb
---
apiVersion: v1
kind: Service
metadata:
  name: authdb
spec:
  ports:
    - port: 3306
  selector:
    app: authdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guilddb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guilddb
  template:
    metadata:
      labels:
        app: guilddb
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: guilddb
          image: mysql:8.0.20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 3306
              name: guilddb
---
apiVersion: v1
kind: Service
metadata:
  name: guilddb
spec:
  ports:
    - port: 3306
  selector:
    app: guilddb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jking-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jking-auth
  template:
    metadata:
      labels:
        app: jking-auth
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: jking-auth
          image: jkingcontainterregistry01.azurecr.io/jking-auth:v1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8082
              name: jking-auth
---
apiVersion: v1
kind: Service
metadata:
  name: jking-auth
spec:
  type: LoadBalancer
  ports:
    - port: 8082
  selector:
    app: jking-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jking-guild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jking-guild
  template:
    metadata:
      labels:
        app: jking-guild
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: jking-guild
          image: jkingcontainterregistry01.azurecr.io/jking-guild:v1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8081
          env:
            - name: jking-auth
              value: "jking-auth"
---
apiVersion: v1
kind: Service
metadata:
  name: jking-guild
spec:
  type: LoadBalancer
  ports:
    - port: 8081
  selector:
    app: jking-guild
