apiVersion: v1
kind: Service
metadata:
  name: authdb
spec:
  ports:
    - port: 3306
  selector:
    app: authdb
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: authdb
spec:
  selector:
    matchLabels:
      app: authdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: authdb
    spec:
      containers:
        - image: mysql:8.0.20
          name: authdb
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: 'password'
            - name: MYSQL_DATABASE
              value: 'authdb'
            - name: MYSQL_USER
              value: 'user'
            - name: MYSQL_PASSWORD
              value: 'password'
          ports:
            - containerPort: 3306
              name: authdb
---
apiVersion: v1
kind: Service
metadata:
  name: guilddb
spec:
  ports:
    - port: 3306
  selector:
    app: guilddb
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: guilddb
spec:
  selector:
    matchLabels:
      app: guilddb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: guilddb
    spec:
      containers:
        - image: mysql:8.0.20
          name: guilddb
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: 'password'
            - name: MYSQL_DATABASE
              value: 'guilddb'
            - name: MYSQL_USER
              value: 'user'
            - name: MYSQL_PASSWORD
              value: 'password'
          ports:
            - containerPort: 3306
              name: guilddb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: message-broker
          image: rabbitmq:3.8-management
          ports:
            - containerPort: 5672
              name: message-broker
---
apiVersion: v1
kind: Service
metadata:
  name: message-broker
spec:
  type: LoadBalancer
  ports:
    - port: 5672
  selector:
    app: message-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jking-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jking-auth
  template:
    metadata:
      labels:
        app: jking-auth
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: jking-auth
          image: jkingcontainterregistry01.azurecr.io/jking-auth:kube
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8082
              name: jking-auth
---
apiVersion: v1
kind: Service
metadata:
  name: jking-auth
spec:
  type: LoadBalancer
  ports:
    - port: 8082
  selector:
    app: jking-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jking-guild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jking-guild
  template:
    metadata:
      labels:
        app: jking-guild
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: jking-guild
          image: jkingcontainterregistry01.azurecr.io/jking-guild:kube
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8081
          env:
            - name: jking-auth
              value: "jking-auth"
---
apiVersion: v1
kind: Service
metadata:
  name: jking-guild
spec:
  type: LoadBalancer
  ports:
    - port: 8081
  selector:
    app: jking-guild
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar
spec:
  replicas: 1
  template:
    metadata:
      name: sonar
      labels:
        name: sonar
    spec:
      containers:
        - image: sonarqube:latest
          command: ["wget"]
          args: ["-O", "/etc/sysctl.d/60-elasticsearch.conf", "https://www.dropbox.com/s/5kelvpq7vo43jmb/60-elasticsearch.conf?dl=1"]
          name: sonar
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              value: password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonar-postgres:5432/sonar
          ports:
            - containerPort: 9000
              name: sonar

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar
  name: sonar
spec:
  ports:
    - port: 80
      targetPort: 9000
      name: sonarport
  selector:
    name: sonar
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar-postgres
spec:
  replicas: 1
  template:
    metadata:
      name: sonar-postgres
      labels:
        name: sonar-postgres
    spec:
      containers:
        - image: postgres:9.5.3
          name: sonar-postgres
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: sonar
          ports:
            - containerPort: 5432
              name: postgresport
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar-postgres
  name: sonar-postgres
spec:
  ports:
    - port: 5432
  selector:
    name: sonar-postgres
---

